"""Model-side contracts for the kernel."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal, Protocol

from .types import ExecutionContext


Role = Literal["system", "user", "assistant", "tool"]


@dataclass(frozen=True)
class ModelMessage:
    """Canonical message exchanged with model providers."""

    role: Role
    content: str
    name: str = ""
    tool_call_id: str = ""
    tool_calls: tuple["ModelToolCall", ...] = ()


@dataclass
class ModelToolCall:
    """Tool call generated by a model provider."""

    call_id: str
    name: str
    arguments: dict[str, Any] = field(default_factory=dict)


@dataclass
class ModelRequest:
    """Input payload for model generation."""

    messages: tuple[ModelMessage, ...]
    tools: tuple[dict[str, Any], ...] = ()
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class ModelResponse:
    """Output payload from model generation."""

    text: str = ""
    tool_calls: tuple[ModelToolCall, ...] = ()
    finish_reason: str = "stop"
    metadata: dict[str, Any] = field(default_factory=dict)


class ModelProvider(Protocol):
    """Unified model provider contract."""

    async def generate(
        self,
        request: ModelRequest,
        context: ExecutionContext,
    ) -> ModelResponse:
        ...
